Update workflow.md
ecaresoft/guides pull request #1
Opened 2017-03-15 19:31 UTC by jcantupena

2017-03-15 20:07 UTC, jcmrgo requested changes
@jcantupena podrias tambien actualizar la linea 167 del documento de una vez?

`git merge release-[YYYYMMDD]-[HHMM]` 
por 
`git merge Release-[VxRd.dd]`

2017-03-15 20:27 UTC, jcantupena commented
Hola @jcmrgo ya se realizó la modificación que solicitaste.

2017-03-15 20:33 UTC, benoror commented
@jcantupena @jcmrgo for the record esta pendiente agregar el flujo del Hotfix que veamos mañana cuando integremos el Ticket de @rreynaecs

2017-03-16 22:09 UTC, jcmrgo approved these changes

2017-03-22 19:02 UTC, merged